Refactor bootloader setup and filesystem handling

diff --git a/base_install b/base_install
--- a/base_install
+++ b/base_install
@@ -35,20 +35,18 @@ FileSystemFormat () {
 	mkswap "$SWAP_PART" || SHOWerror "mkswap"; SWAPID="$(blkid -s "$PIDsel" -o value "$SWAP_PART")" || SHOWerror "blkid SWAPID"
 	UNIfstab="$PIDsel=$BOOTID /boot vfat defaults 0 2\n$PIDsel=$SWAPID none swap defaults 0 0\n"
 	case "$FSsel" in
-		ext4)  mkfs.ext4 -L "$RootLabel" "$ROOT_PART" || SHOWerror "mkfs.ext4 ROOT"; ROOTID="$(blkid -s "$PIDsel" -o value "$ROOT_PART")" || SHOWerror "blkid ROOTID ext4"; mount "$ROOT_PART" /mnt || SHOWerror "mount ext4 root"; UNIfstab+="$PIDsel=$ROOTID / ext4 defaults 0 1\n" ;;
-		btrfs) modules=(btrfs); binaries='btrfs'; local SUBVolumes=( 'home' 'var_log' 'var_cache' 'snapshots' ); local options='noatime,compress=zstd,space_cache=v2,discard=async'
-			   mkfs.btrfs -fL "$RootLabel" "$ROOT_PART" || SHOWerror "mkfs.btrfs ROOT"; ROOTID="$(blkid -s "$PIDsel" -o value "$ROOT_PART")" || SHOWerror "blkid ROOTID btrfs"
-			   mount "$ROOT_PART" /mnt || SHOWerror "mount btrfs root"; btrfs su cr /mnt/@ || SHOWerror "btrfs subvol @"
-			   for b in "${SUBVolumes[@]}"; do btrfs su cr /mnt/@"$b" || SHOWerror "btrfs subvol @$b"; done; umount /mnt || SHOWerror "umount btrfs root setup"
-			   mount -o defaults,"$options",subvol=@ "$ROOT_PART" /mnt || SHOWerror "mount btrfs subvol @"
-			   UNIfstab+="$PIDsel=$ROOTID / btrfs $options,subvol=@ 0 0\n"
-			   for c in "${SUBVolumes[@]}"; do
-				   case "$c" in
-					   snapshots) mkdir -p /mnt/."$c" && mount -o "$options",subvol=@"$c" "$ROOT_PART" /mnt/."$c" || SHOWerror "mount @snapshots"; UNIfstab+="$PIDsel=$ROOTID /.$c btrfs $options,subvol=@$c 0 0\n" ;;
-					   var_log)   mkdir -p /mnt/var/log && mount -o "$options",subvol=@"$c" "$ROOT_PART" /mnt/var/log || SHOWerror "mount @var_log"; UNIfstab+="$PIDsel=$ROOTID /var/log btrfs $options,subvol=@$c 0 0\n" ;;
-					   *)         mkdir -p /mnt/"$c" && mount -o defaults,"$options",subvol=@"$c" "$ROOT_PART" /mnt/"$c" || SHOWerror "mount @$c"; UNIfstab+="$PIDsel=$ROOTID /$c btrfs $options,subvol=@$c 0 0\n" ;;
-				   esac
-			   done ;;
+		ext4)	mkfs.ext4 -L "$RootLabel" "$ROOT_PART" || SHOWerror "mkfs.ext4 ROOT"; ROOTID="$(blkid -s "$PIDsel" -o value "$ROOT_PART")" || SHOWerror "blkid ROOTID ext4"; mount "$ROOT_PART" /mnt || SHOWerror "mount ext4 root"; UNIfstab+="$PIDsel=$ROOTID / ext4 defaults 0 1\n" ;;
+		btrfs)	modules=(btrfs); binaries='btrfs'; local SUBVolumes=( 'home' 'var_log' 'var_cache' 'snapshots' ); local options='noatime,compress=zstd,space_cache=v2,discard=async'
+				mkfs.btrfs -fL "$RootLabel" "$ROOT_PART" || SHOWerror "mkfs.btrfs ROOT"; ROOTID="$(blkid -s "$PIDsel" -o value "$ROOT_PART")" || SHOWerror "blkid ROOTID btrfs"
+				mount "$ROOT_PART" /mnt || SHOWerror "mount btrfs root"; btrfs su cr /mnt/@ || SHOWerror "btrfs subvol @"
+				for b in "${SUBVolumes[@]}"; do btrfs su cr /mnt/@"$b" || SHOWerror "btrfs subvol @$b"; done; umount /mnt || SHOWerror "umount btrfs root setup"
+				mount -o defaults,"$options",subvol=@ "$ROOT_PART" /mnt || SHOWerror "mount btrfs subvol @"
+				UNIfstab+="$PIDsel=$ROOTID / btrfs $options,subvol=@ 0 0\n"
+				for c in "${SUBVolumes[@]}"; do
+					local d_path="/$c"; [[ "$c" == "snapshots" ]] && d_path="/.$c"; [[ "$c" == "var_log" ]] && d_path="/var/log"
+					mkdir -p "/mnt$d_path" && mount -o defaults,"$options",subvol=@"$c" "$ROOT_PART" "/mnt$d_path" || SHOWerror "mount @$c"
+					UNIfstab+="$PIDsel=$ROOTID $d_path btrfs $options,subvol=@$c 0 0\n"
+				done ;;
 		*) SHOWerror "Unsupported file system selection" ;;
 	esac
 	export BOOTID ROOTID SWAPID
@@ -123,7 +121,7 @@ PackageInstall () {
 	local VBTboot=(); [[ "$BLsel" == "efistub" ]] && VBTboot+=(efibootmgr); [[ "$BLsel" == "grub" ]] && VBTboot+=(grub); [[ "$BLsel" == "refind" ]] && VBTboot+=(refind); [[ "$FSsel" == "btrfs" ]] && VBTboot+=(btrfs-progs)
 	if [[ "$VBTsel" -eq 1 ]]; then [[ "${OSsel,,}" == "void" ]] && "$chroot" /mnt "$PKGmanager" "${pkgskips[@]}" -S "${VBTboot[@]}" || "$chroot" /mnt "$PKGmanager" -Syu "${pkgskips[@]}" "${baselinux[@]}" "${baseutils[@]}" "${elogind[@]}" "${net[@]}" "${bluetooth[@]}" "${print[@]}" "${VBTboot[@]}"
 	else local FullPKGs=( "${microcode[@]}" "${kernel[@]}" "${baseutils[@]}" "${fs[@]}" "${bootloaderutility[@]}" "${btrfsutility[@]}" "${grubpkg[@]}" "${refindpkg[@]}" "${net[@]}" "${audio[@]}" "${bluetooth[@]}" "${android[@]}" "${print[@]}" "${apps[@]}" "${utility[@]}" "${hardwareacceleration[@]}" "${vulkan[@]}" "${filemanager[@]}" "${archive[@]}" )
-		[[ -v nvidiadrivers && ${#nvidiadrivers[@]} -gt 0 ]] && FullPKGs+=( "${nvidiadrivers[@]}" )
+		[[ ${#nvidiadrivers[@]} -gt 0 ]] && FullPKGs+=( "${nvidiadrivers[@]}" )
 		[[ -v amddrivers && ${#amddrivers[@]} -gt 0 ]] && FullPKGs+=( "${amddrivers[@]}" )
 		[[ "${OSsel,,}" == "void" ]] || FullPKGs+=( "${baselinux[@]}" "${elogind[@]}" "${grubbtrfs[@]}" "${personalization[@]}" )
 		[[ "${OSsel,,}" == "void" ]] && "$chroot" /mnt "$PKGmanager" "${pkgskips[@]}" -S "${FullPKGs[@]}" || "$chroot" /mnt "$PKGmanager" -Syu "${pkgskips[@]}" "${FullPKGs[@]}"
@@ -168,7 +166,7 @@ KernelSetup () {
 		intel-ucode) echo -e 'options i915 enable_fbc=1 fastboot=0 enable_dc=4' >> /mnt/etc/modprobe.d/i915.conf || SHOWerror "i915 modprobe options" ;;
 		*) echo 'AMD or generic setup: Nothing at the moment' ;;
 	esac
-	if [[ -v nvidiadrivers && ${#nvidiadrivers[@]} -gt 0 ]]; then
+	if [[ ${#nvidiadrivers[@]} -gt 0 ]]; then
 		[[ "${OSsel,,}" == "artix" ]] && { "$chroot" /mnt "$PKGmanager" -Syu "${pkgskips[@]}" nvidia-utils-openrc || SHOWerror "artix nvidia-utils-openrc"; }
 		ln -s /dev/null /mnt/etc/udev/rules.d/61-gdm.rules || SHOWerror "61-gdm udev rule link"; modules+=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)
 		echo -e "options nvidia-drm modeset=1 fbdev=1\noptions nvidia NVreg_DynamicPowerManagement=0x02 NVreg_UsePageAttributeTable=1 NVreg_EnablePCIeGen3=1" > /mnt/etc/modprobe.d/nvidia.conf || SHOWerror "nvidia modprobe options"
@@ -177,7 +175,7 @@ KernelSetup () {
 		dracut)	mkdir -p /mnt/etc/dracut.conf.d || SHOWerror "mkdir dracut.conf.d"
 				[[ "${OSsel,,}" == "void" ]] && { "$chroot" /mnt "$PKGmanager" "${pkgskips[@]}" -S dracut || SHOWerror "Void dracut install"; }
 				[[ "$FSsel" == "btrfs" ]] && { echo 'add_dracutmodules+=" btrfs "' > /mnt/etc/dracut.conf.d/btrfs.conf || SHOWerror "dracut btrfs conf"; }
-				[[ -v nvidiadrivers && ${#nvidiadrivers[@]} -gt 0 ]] && { echo 'force_drivers+=" nvidia nvidia_modeset nvidia_uvm nvidia_drm "' > /mnt/etc/dracut.conf.d/nvidia.conf || SHOWerror "dracut nvidia conf"; }
+				[[ ${#nvidiadrivers[@]} -gt 0 ]] && { echo 'force_drivers+=" nvidia nvidia_modeset nvidia_uvm nvidia_drm "' > /mnt/etc/dracut.conf.d/nvidia.conf || SHOWerror "dracut nvidia conf"; }
 				"$chroot" /mnt xbps-reconfigure -f "$KSel" || SHOWerror "xbps-reconfigure dracut" ;;
 		booster) [[ ${#booster[@]} -gt 0 ]] && { "$chroot" /mnt "$PKGmanager" -Syu "${pkgskips[@]}" "${booster[@]}" || SHOWerror "install booster"; }
 				[[ "${OSsel,,}" != "void" ]] && { "$chroot" /mnt pacman -Rns --noconfirm mkinitcpio || SHOWerror "purge mkinitcpio"; }
@@ -185,12 +183,12 @@ KernelSetup () {
 				echo "resume: /dev/disk/by-uuid/${SWAPID}" >> /mnt/etc/booster.yaml || SHOWerror "booster.yaml resume inject"
 				if [[ "$VBTsel" -eq 1 ]]; then [[ "$FSsel" == "btrfs" ]] && echo 'modules: btrfs,ahci,ata_piix,sd_mod,nvme' >> /mnt/etc/booster.yaml || echo 'modules: ahci,ata_piix,sd_mod,nvme' >> /mnt/etc/booster.yaml
 				else [[ "$FSsel" == "btrfs" ]] && echo 'modules: btrfs' >> /mnt/etc/booster.yaml; fi
-				[[ -v nvidiadrivers && ${#nvidiadrivers[@]} -gt 0 ]] && { echo 'modules: nvidia,nvidia_modeset,nvidia_uvm,nvidia_drm' >> /mnt/etc/booster.yaml || SHOWerror "booster.yaml nvidia inject"; }
+				[[ ${#nvidiadrivers[@]} -gt 0 ]] && { echo 'modules: nvidia,nvidia_modeset,nvidia_uvm,nvidia_drm' >> /mnt/etc/booster.yaml || SHOWerror "booster.yaml nvidia inject"; }
 				if [[ "${OSsel,,}" != "void" ]]; then mkdir -p /mnt/etc/pacman.d/hooks || SHOWerror "mkdir pacman hooks"
 				printf '[Trigger]\nOperation = Install\nOperation = Upgrade\nType = Package\nTarget = %s\n\n[Action]\nDescription = Forcing Booster initramfs update...\nWhen = PostTransaction\nDepends = booster\nExec = /usr/bin/booster build --force --universal /boot/initramfs-%s.img\n' "$KSel" "$KSel" > /mnt/etc/pacman.d/hooks/95-booster-force.hook || SHOWerror "booster-force hook creation"; fi
 				local real_kver; real_kver=$(basename "$(find /mnt/usr/lib/modules/ -maxdepth 1 -mindepth 1 -type d ! -name 'extramodules*' | head -n 1)") || SHOWerror "find real_kver"
 				"$chroot" /mnt /bin/bash -c "booster build --force --universal --kernel-version=${real_kver} /boot/initramfs-${KSel}.img" || SHOWerror "booster build" ;;
-		*) local HOOKS=(base udev autodetect modconf block usr resume filesystems keyboard keymap fsck); [[ -v nvidiadrivers && ${#nvidiadrivers[@]} -gt 0 ]] && HOOKS+=(kms)
+		*) local HOOKS=(base udev autodetect modconf block usr resume filesystems keyboard keymap fsck); [[ ${#nvidiadrivers[@]} -gt 0 ]] && HOOKS+=(kms)
 		   sed -i "/MODULES/ s/()/(${modules[*]})/" /mnt/etc/mkinitcpio.conf || SHOWerror "mkinitcpio modules inject"
 		   sed -i "/BINARIES/ s/()/($binaries)/" /mnt/etc/mkinitcpio.conf
 		   sed -i "s/^HOOKS.*/HOOKS=(${HOOKS[*]})/" /mnt/etc/mkinitcpio.conf || SHOWerror "mkinitcpio hooks inject"
@@ -221,45 +219,37 @@ AudioSetup () {
 }
 BootloaderSetup () {
 	local osi_version="${AcpiOS:-Windows 2020}"; local kname; kname=$(basename "$(find /mnt/boot/ -type f -name 'vmlinuz-*' | head -n 1)") || kname="vmlinuz-$KSel"
+	local irfs initrd_flags rootflags="" nvdrm="" nvosi=""
+	[[ "${OSsel,,}" == "void" ]] && irfs="initramfs-${kname#vmlinuz-}.img" || irfs="initramfs-$KSel.img"
+	[[ "$FSsel" == "btrfs" ]] && rootflags='rootflags=subvol=@'
+	[[ ${#nvidiadrivers[@]} -gt 0 ]] && { nvdrm="nvidia-drm.modeset=1 nvidia-drm.fbdev=1"; nvosi="acpi_osi=\"$osi_version\""; }
+	[[ "$IRFSetup" == "booster" || "${OSsel,,}" == "void" ]] && initrd_flags="initrd=\\${irfs}" || initrd_flags="initrd=\\${microcodepkg}.img initrd=\\${irfs}"
 	case "$BLsel" in
-		1|REFIND|Refind|refind)
-			irfs="initramfs-$KSel.img"
-			"$chroot" /mnt "$PKGmanager" -Sy "${pkgskips[@]}" "${refindpkg[@]}" || SHOWerror "rEFInd package install"
-			"$chroot" /mnt refind-install || SHOWerror "rEFInd execution"; [[ "$UEFImode" -eq 1 ]] && efifolder='refind' || efifolder='BOOT'
-			mkdir -p /mnt/boot/EFI/"$efifolder"/themes || SHOWerror "mkdir rEFInd themes"
-			cp -r "${SCRIPT_DIR}/Bootloader/Refind/themes/"* /mnt/boot/EFI/"$efifolder"/themes/ || SHOWerror "Copy rEFInd themes"
-			grep -q "theme.conf" /mnt/boot/EFI/"$efifolder"/refind.conf || echo "include themes/Blur-theme/theme.conf" >> /mnt/boot/EFI/"$efifolder"/refind.conf
-			[[ "$VBTsel" -eq 1 ]] && { sed -i 's/#resolution 1024 768/resolution 1024 768/' /mnt/boot/EFI/"$efifolder"/refind.conf || SHOWerror "Sed rEFInd resolution"; }
-			[[ "$FSsel" == "btrfs" ]] && rootflags='rootflags=subvol=@'
-			[[ -v nvidiadrivers && ${#nvidiadrivers[@]} -gt 0 ]] && drm="nvidia-drm.modeset=1 nvidia-drm.fbdev=1 acpi_osi=\"$osi_version\""
-			if [[ "$IRFSetup" == "booster" ]]; then initrd_flags="initrd=\\${irfs}"
-			else [[ "${OSsel,,}" == "void" ]] && initrd_flags="initrd=\\${irfs}" || initrd_flags="initrd=\\${microcodepkg}.img initrd=\\${irfs}"; fi
-			echo "\"Standard Boot\"   \"ro root=${PIDsel}=$ROOTID resume=${PIDsel}=$SWAPID rootfstype=$FSsel $rootflags $initrd_flags $drm\"" > /mnt/boot/refind_linux.conf || SHOWerror "Write refind_linux.conf"
-			echo '!!!Refind config and theme changed!!!' ;;
-		2|GRUB|Grub|grub)
-			[[ "$FSsel" == "btrfs" ]] && grubpkg+=("${grubbtrfs[@]}")
-			"$chroot" /mnt "$PKGmanager" -Sy "${pkgskips[@]}" "${grubpkg[@]}" || SHOWerror "GRUB package install"
-			if [[ "$UEFImode" -eq 0 ]]; then "$chroot" /mnt grub-install --target=i386-pc --recheck --debug "$DRIVE" || SHOWerror "GRUB BIOS install"
-			else "$chroot" /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB || SHOWerror "GRUB UEFI install"; fi
-			mkdir -p /mnt/boot/grub/themes || SHOWerror "mkdir GRUB themes"
-			sed -i "/GRUB_DISABLE_OS_PROBER=/ s/#//g" /mnt/etc/default/grub || SHOWerror "Sed GRUB os-prober"
-			sed -i '/GRUB_THEME=/c GRUB_THEME="/boot/grub/themes/Grub-Sekiro/theme.txt"' /mnt/etc/default/grub || SHOWerror "Sed GRUB theme selection"
-			[[ -v nvidiadrivers && ${#nvidiadrivers[@]} -gt 0 ]] && { sed -i -e "s/^GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX=\"acpi_osi='\$osi_version'\"/" -e 's/^GRUB_CMDLINE_LINUX_DEFAULT="\(.*\)"/GRUB_CMDLINE_LINUX_DEFAULT="\1 quiet splash nvidia-drm.modeset=1 nvidia-drm.fbdev=1"/' /mnt/etc/default/grub || SHOWerror "Sed GRUB nvidia injection"; }
-			mkdir -p /mnt/usr/share/grub/themes/ || SHOWerror "mkdir usr share GRUB themes"
-			cp -r "${SCRIPT_DIR}/Bootloader/Grub-Sekiro" /mnt/boot/grub/themes/ || SHOWerror "Copy Sekiro theme to /boot"
-			cp -r "${SCRIPT_DIR}/Bootloader/Grub-Sekiro" /mnt/usr/share/grub/themes/ || SHOWerror "Copy Sekiro theme to /usr"
-			"$chroot" /mnt grub-mkconfig -o /boot/grub/grub.cfg || SHOWerror "GRUB mkconfig execution" ;;
-		3|EFISTUB|Efistub|efistub)
-			local initrd_flags; [[ "$FSsel" == "btrfs" ]] && rootflags='rootflags=subvol=@'
-			[[ -v nvidiadrivers && ${#nvidiadrivers[@]} -gt 0 ]] && osi="nvidia-drm.modeset=1 nvidia-drm.fbdev=1 acpi_osi=\"$osi_version\""
-			[[ "${OSsel,,}" == "void" ]] && irfs="initramfs-${kname#vmlinuz-}.img" || irfs="initramfs-$KSel.img"
-			if [[ "$IRFSetup" == "booster" ]]; then initrd_flags="initrd=\\${irfs}"
-			else [[ "${OSsel,,}" == "void" ]] && initrd_flags="initrd=\\${irfs}" || initrd_flags="initrd=\\${microcodepkg}.img initrd=\\${irfs}"; fi
-			BLflags=" $initrd_flags ro root=${PIDsel}=$ROOTID resume=${PIDsel}=$SWAPID rootfstype=$FSsel $rootflags $osi"
-			local efi_dev="${DRIVEsel:-$DRIVE}"; local efi_num="$(echo "$BOOT_PART" | grep -o '[0-9]*$')"
-			"$chroot" /mnt efibootmgr -d "$efi_dev" -p "${efi_num:-1}" -c -L "$OSsel" -l "\\$kname" -u "$BLflags" --verbose || SHOWerror "Efibootmgr execution"
-			echo "efibootmgr -b lastnumber -B" ;;
-	esac
+        1|REFIND|Refind|refind)
+            "$chroot" /mnt "$PKGmanager" -Sy "${pkgskips[@]}" "${refindpkg[@]}" || SHOWerror "rEFInd package install"
+            "$chroot" /mnt refind-install || SHOWerror "rEFInd execution"; [[ "$UEFImode" -eq 1 ]] && efifolder='refind' || efifolder='BOOT'
+            mkdir -p /mnt/boot/EFI/"$efifolder"/themes || SHOWerror "mkdir rEFInd themes"
+            cp -r "${SCRIPT_DIR}/Bootloader/Refind/themes/"* /mnt/boot/EFI/"$efifolder"/themes/ || SHOWerror "Copy rEFInd themes"
+            grep -q "theme.conf" /mnt/boot/EFI/"$efifolder"/refind.conf || echo "include themes/Blur-theme/theme.conf" >> /mnt/boot/EFI/"$efifolder"/refind.conf
+            [[ "$VBTsel" -eq 1 ]] && sed -i 's/#resolution 1024 768/resolution 1024 768/' /mnt/boot/EFI/"$efifolder"/refind.conf
+            echo "\"Standard Boot\"   \"ro root=${PIDsel}=$ROOTID resume=${PIDsel}=$SWAPID rootfstype=$FSsel $rootflags $initrd_flags $nvdrm $nvosi\"" > /mnt/boot/refind_linux.conf || SHOWerror "Write refind_linux.conf"
+            echo '!!!Refind config and theme changed!!!' ;;
+        2|GRUB|Grub|grub)
+            [[ "$FSsel" == "btrfs" ]] && grubpkg+=("${grubbtrfs[@]}")
+            "$chroot" /mnt "$PKGmanager" -Sy "${pkgskips[@]}" "${grubpkg[@]}" || SHOWerror "GRUB package install"
+            if [[ "$UEFImode" -eq 0 ]]; then "$chroot" /mnt grub-install --target=i386-pc --recheck --debug "$DRIVE" || SHOWerror "GRUB BIOS install"
+            else "$chroot" /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB || SHOWerror "GRUB UEFI install"; fi
+            mkdir -p /mnt/boot/grub/themes /mnt/usr/share/grub/themes/ || SHOWerror "mkdir GRUB themes"
+            sed -i "/GRUB_DISABLE_OS_PROBER=/ s/#//g" /mnt/etc/default/grub
+            sed -i '/GRUB_THEME=/c GRUB_THEME="/boot/grub/themes/Grub-Sekiro/theme.txt"' /mnt/etc/default/grub
+            [[ ${#nvidiadrivers[@]} -gt 0 ]] && sed -i -e "s/^GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX=\"$nvosi\"/" -e "s/^GRUB_CMDLINE_LINUX_DEFAULT=\"\(.*\)\"/GRUB_CMDLINE_LINUX_DEFAULT=\"\1 quiet splash $nvdrm\"/" /mnt/etc/default/grub
+            cp -r "${SCRIPT_DIR}/Bootloader/Grub-Sekiro" /mnt/boot/grub/themes/ && cp -r "${SCRIPT_DIR}/Bootloader/Grub-Sekiro" /mnt/usr/share/grub/themes/ || SHOWerror "Copy Sekiro theme"
+            "$chroot" /mnt grub-mkconfig -o /boot/grub/grub.cfg || SHOWerror "GRUB mkconfig execution" ;;
+        3|EFISTUB|Efistub|efistub)
+            local BLflags=" $initrd_flags ro root=${PIDsel}=$ROOTID resume=${PIDsel}=$SWAPID rootfstype=$FSsel $rootflags $nvdrm $nvosi"
+            local efi_dev="${DRIVEsel:-$DRIVE}"; local efi_num="$(echo "$BOOT_PART" | grep -o '[0-9]*$')"
+            "$chroot" /mnt efibootmgr -d "$efi_dev" -p "${efi_num:-1}" -c -L "$OSsel" -l "\\$kname" -u "$BLflags" --verbose || SHOWerror "Efibootmgr execution" ;;
+    esac
 }
 InstallationSetup () {
 	VBTsel=0; SetupAvaible=1; CheckandSetup=( Check_required_files UEFIsel CPUsel KernelSel IRFsel BootloaderSel GPUsel Pacman_Locked )
