Update base_install

diff --git a/base_install b/base_install
--- a/base_install
+++ b/base_install
@@ -65,9 +65,9 @@ FileSystemFormat () {
 		   UNIfstab+="$PIDsel=$ROOTID / btrfs $options,subvol=@ 0 0\n"
 		   for c in "${SUBVolumes[@]}"; do
 			   case "$c" in
-			   snapshots) mkdir -p /mnt/."$c" ; mount -o "$options" "$ROOT_PART" /mnt/."$c"
-						  UNIfstab+="$PIDsel=$ROOTID /.$c btrfs $options,subvol=@$c 0 0\n" ;;
-			   var_log)   mkdir -p /mnt/var/log ; mount -o "$options" "$ROOT_PART" /mnt/var/log
+			   snapshots) mkdir -p /mnt/."$c" ; mount -o "$options",subvol=@"$c" "$ROOT_PART" /mnt/."$c" ;;
+							UNIfstab+="$PIDsel=$ROOTID /.$c btrfs $options,subvol=@$c 0 0\n" ;;
+			   var_log)  mkdir -p /mnt/var/log ; mount -o "$options",subvol=@"$c" "$ROOT_PART" /mnt/var/log ;;
 						  UNIfstab+="$PIDsel=$ROOTID /var/log btrfs $options,subvol=@$c 0 0\n" ;;
 			   swap)      ;;
 			   *)         mkdir -p /mnt/"$c" && mount -o defaults,"$options",subvol=@"$c" "$ROOT_PART" /mnt/"$c"
@@ -88,54 +88,46 @@ AdditionalDriveSetup () {
 }
 
 BaseSystemInstall () {
-	local BasePKG=( "${kernel[@]}" "${baselinux[@]}"  "${elogind[@]}" "${btrfspkg[@]}" )
-	if [ "$FSsel" = btrfs ]; then BasePKG+=( "${btrfsutility[@]}" ); fi
-	"$PKGstrap" /mnt "${microcode[@]}" "${BasePKG[@]}"
+	local BasePKG=( "${kernel[@]}" "${baselinux[@]}" "${elogind[@]}" "${btrfspkg[@]}" )
+	[ "$FSsel" = btrfs ] && BasePKG+=( "${btrfsutility[@]}" )
+	"$PKGstrap" /mnt "$microcodepkg" "${BasePKG[@]}"
 }
 
 FStabGen () {
-	mv -f /mnt/etc/fstab /mnt/etc/old-fstab
+	mv -f /mnt/etc/fstab /mnt/etc/old-fstab 2>/dev/null || true
 	if [[ "$OSsel" = Void ]]; then echo -e "$UNIfstab" > /mnt/etc/fstab
 	elif [ -v PIDsel ]; then "$fstabgen" -t "$PIDsel" /mnt >> /mnt/etc/fstab
-	else exit 1
-	fi
+	else exit 1 ; fi
 	cat /mnt/etc/fstab
 }
 
 SetupEnvironment () {
-	#sed -i "/$LOCsel/ s/#//g" /mnt/etc/locale.gen
 	sed -i "/\($LOCsel\|$LANGsel\)/ s/#//g" /mnt/etc/locale.gen
-	echo -e "LANG=$LOCsel \nLANGUAGE=$LANGsel \nLC_TIME=$LOCsel \nLC_ADDRESS=$LOCsel \nLC_MESSAGES=$LOCsel \nLC_CTYPE=C" >> /mnt/etc/locale.conf
-	echo "$keylayout" | tee /mnt/"$keypath" /mnt/etc/vconsole.conf
-	"chroot" /mnt ln -sf /usr/share/zoneinfo/"$TZsel" /etc/localtime
-	"chroot" /mnt hwclock --systohc --utc
-	"chroot" /mnt locale-gen
-	#echo -e "HARDWARECLOCK=$HARDWARECLOCK \nKEYMAP=$KEYMAP \nFONT=$FONT \nTTYS=$TTYS" >> /mnt/etc/rc.conf
-	echo "$HNsel" >> /mnt/etc/hostname
-	echo -e " $HNsel \n 127.0.0.1 localhost \n ::1 localhost \n 127.0.1.1 $HNsel.localdomain $HNsel" >> /mnt/etc/hosts
+	echo -e "LANG=$LOCsel\nLANGUAGE=$LANGsel\nLC_TIME=$LOCsel\nLC_ADDRESS=$LOCsel\nLC_MESSAGES=$LOCsel\nLC_CTYPE=C" >> /mnt/etc/locale.conf
+	echo "$keylayout" | tee /mnt/"$keypath" /mnt/etc/vconsole.conf >/dev/null
+	"$chroot" /mnt ln -sf /usr/share/zoneinfo/"$TZsel" /etc/localtime
+	"$chroot" /mnt hwclock --systohc --utc ; "$chroot" /mnt locale-gen
+	echo "$HNsel" > /mnt/etc/hostname
+	echo -e "127.0.0.1\tlocalhost\n::1\t\tlocalhost\n127.0.1.1\t$HNsel.localdomain $HNsel" >> /mnt/etc/hosts
 }
 
 PackageConfig () {
 	"$chroot" /mnt "$PKGmanager" -Sy
 	case "$OSsel" in
-	1|arch|Arch)	sed -i '/\[multilib]/,/mirrorlist/ s/#//' /mnt/etc/pacman.conf ;;
-	2|artix|Artix)	sed -i '/\[lib32]/,/mirrorlist/ s/#//' /mnt/etc/pacman.conf
-		if [ "$ARCHrepo" = 1 ]; then ArchRepoSetup /mnt/etc/pacman.conf ; fi
-	;;
-	3|void|Void)	;;
-	*)	echo "No distro selected, there is a problem with additional_setup, exiting..." && exit 1 ;;
+	1|Arch|arch)   sed -i '/\[multilib]/,/mirrorlist/ s/#//' /mnt/etc/pacman.conf ;;
+	2|Artix|artix) sed -i '/\[lib32]/,/mirrorlist/ s/#//' /mnt/etc/pacman.conf
+				   [ "$ARCHrepo" = 1 ] && ArchRepoSetup /mnt/etc/pacman.conf ;;
+	3|Void|void)   ;;
+	*) echo "Error distro configuration" && exit 1 ;;
 	esac
 	sed -i '/\(Color\|ParallelDownloads\)/ s/#//' /mnt/etc/pacman.conf
 	sed -i '/ParallelDownloads/a ILoveCandy' /mnt/etc/pacman.conf
 }
 
 PackageInstall () {
-	if [[ -v nvidiadrivers ]]; then vulkanlib32+=(lib32-vulkan-nvidia); fi
-	local EssentialPKG=( "${microcode[@]}"  "${kernel[@]}" "${baselinux[@]}" "${baseutils[@]}" "${bootloaderutility[@]}" "${fs[@]}" "${amddrivers[@]}" "${nvidiadrivers[@]}"  "${net[@]}" )
-	local AdditionalPKG=( "${audio[@]}" "${bluetooth[@]}" "${battery[@]}" "${android[@]}" "${print[@]}" "${utility[@]}" "${hardwareacceleration[@]}" "${vulkan[@]}" "${vulkanlib32[@]}" "${apps[@]}" "${personalization[@]}" )
-	local ExtraPKG=( "${filemanager[@]}" "${archive[@]}" "${xorg[@]}" )
-	if [[ "$VBTsel" = 1 ]]; then "$chroot" /mnt "$PKGmanager" -Syu "${pkgskips[@]}" "${EssentialPKG[@]}"
-	else "$chroot" /mnt "$PKGmanager" -Syu "${pkgskips[@]}" "${EssentialPKG[@]}" "${AdditionalPKG[@]}"
+	# I pacchetti validati in memoria vengono iniettati direttamente senza fare passaggi intermedi
+	if [[ "$VBTsel" = 1 ]]; then "$chroot" /mnt "$PKGmanager" -Syu "${pkgskips[@]}" "${_valid[@]}"
+	else "$chroot" /mnt "$PKGmanager" -Syu "${pkgskips[@]}" "${_valid[@]}" "${apps[@]}" "${personalization[@]}"
 	fi
 }
 
@@ -277,9 +269,10 @@ BootloaderSetup () {
 ########## INSTALLATION-PROCESS ##########
 
 InstallationSetup () {
-	VBTsel=0 && SetupAvaible=1 && CheckandSetup=( Check_required_files UEFIsel CPUsel KernelSel GPUsel Pacman_Locked )
-	echo 'List of all errors ocourred during the installation process:' > Errors
+	VBTsel=0 ; SetupAvaible=1 ; CheckandSetup=( Check_required_files UEFIsel CPUsel KernelSel GPUsel Pacman_Locked )
+	echo 'List of all errors occurred during the installation process:' > Errors
 	for c in "${CheckandSetup[@]}"; do "$c" || SHOWerror "$c" ; done
+	
 	if [[ -s config ]]; then
 		cat config && YesNoSel "It's correct?"
 		case "$CC" in 
@@ -296,173 +289,107 @@ InstallationSetup () {
 	
 	if [[ "$SetupAvaible" = 1 ]]; then
 		OperatingSystemSel
-		if [[ "$OSsel" = Artix ]]; then ArchRepoSel ; fi
+		[ "$OSsel" = Artix ] && ArchRepoSel
 		if [[ "$VBTsel" = 1 ]]; then
-			LANGsel='en_GB.UTF-8' && LOCsel='it_IT.UTF-8'
-			HNsel=tarch1 && UNsel=tarch1
-			TZsel='Europe/Rome'
-			PIDsel=UUID && FSsel=btrfs
-			BLsel=refind
-			ArchTixSteps=( 'DiskPartition' 'FileSystemFormat' 'BaseSystemInstall' 'FStabGen' 'SetupEnvironment' 'PackageConfig' 'PackageInstall' 'KernelSetup' 'ServiceSetup' 'UserSetup' 'BootloaderSetup' )
+			LANGsel='en_GB.UTF-8' ; LOCsel='it_IT.UTF-8' ; HNsel=tarch1 ; UNsel=tarch1 ; TZsel='Europe/Rome' ; PIDsel=UUID ; FSsel=btrfs ; BLsel=refind
 		else
 			local Personalization=( LocalizationSel LanguageSel TimezoneSel HostnameSel UsernameSel PartIDSel FilesystemSel BootloaderSel )
-			ArchTixSteps=( 'DiskPartition' 'FileSystemFormat' 'AdditionalDriveSetup' 'BaseSystemInstall' 'FStabGen' 'SetupEnvironment' 'PackageConfig' 'PackageInstall' 'KernelSetup' 'ServiceSetup' 'UserSetup' 'AudioSetup' 'BootloaderSetup' )
+			for s in "${Personalization[@]}"; do "$s" || SHOWerror "$s" ; done
 		fi
-		for s in "${Personalization[@]}"; do "$s" || SHOWerror "$s" ; done
 		Steps=( "OSsel=$OSsel" "ARCHrepo=$ARCHrepo" "LOCsel=$LOCsel" "LANGsel=$LANGsel" "HNsel=$HNsel" "UNsel=$UNsel" "TZsel=$TZsel" "PIDsel=$PIDsel" "FSsel=$FSsel" "BLsel=$BLsel" )
-		if [[ -e config ]]; then rm config ; fi
+		[ -e config ] && rm config
 		for a in "${Steps[@]}"; do echo "$a" ; echo "$a" >> config ; done
 		YesNoSel "It's correct?"
 		case "$CC" in
-		1) echo 'If you say so...' ;;
-		0) YesNoSel "Would you like to edit config file? (Remember to save your config with CRTL+S)"
+		1) echo 'Proceeding...' ;;
+		0) YesNoSel "Would you like to edit config file? (CRTL+S to save)"
 			case $CC in
 			1) nano config ; source config ;;
-			0) "Then start again" && SHOWerror "Second attempt";;
-			*) echo 'Not a good answer' && YesNoSel "Would you like to edit config file?"
+			0) echo "Then start again" && SHOWerror "Second attempt" ;;
+			*) echo 'Not a good answer' && YesNoSel "Would you like to edit config file?" ;;
 			esac ;;
 		*) echo 'Not a good answer' && YesNoSel "It's correct? Otherwise this will end" ;;
 		esac
 	elif [[ "$SetupAvaible" = 0 ]] && [[ -s config ]]; then echo 'Setup loaded'
-	else SHOWerror InstallationSetup
-	fi
+	else SHOWerror InstallationSetup ; fi
+
 	if [[ "$VBTsel" = 1 ]]; then ArchTixSteps=( 'DiskPartition' 'FileSystemFormat' 'BaseSystemInstall' 'FStabGen' 'SetupEnvironment' 'PackageConfig' 'PackageInstall' 'KernelSetup' 'ServiceSetup' 'UserSetup' 'BootloaderSetup' )
 	else ArchTixSteps=( 'DiskPartition' 'FileSystemFormat' 'AdditionalDriveSetup' 'BaseSystemInstall' 'FStabGen' 'SetupEnvironment' 'PackageConfig' 'PackageInstall' 'KernelSetup' 'ServiceSetup' 'UserSetup' 'AudioSetup' 'BootloaderSetup' )
 	fi
 	
 	case "$OSsel" in
 	1|Arch|arch)
-		PKGmanager=pacman
-		pkgskips=( --needed --noconfirm )
-		keylayout='KEYMAP=it'
-		keypath='etc/vconsole.conf'
-		PKGstrap=pacstrap
-		fstabgen=genfstab
-		chroot='arch-chroot'
-		initc0=systemctl
-		initc1=enable
-		sed -i 's/-openrc//g' ../UNI/full_setup
+		PKGmanager=pacman ; pkgskips=( --needed --noconfirm ) ; keylayout='KEYMAP=it' ; keypath='etc/vconsole.conf'
+		PKGstrap=pacstrap ; fstabgen=genfstab ; chroot='arch-chroot' ; initc0=systemctl ; initc1=enable
 		sed -i '/\[multilib]/,/mirrorlist/ s/#//' /etc/pacman.conf
 		pacman -Sylq core extra multilib | sort > pacman_db
-		echo 'Running check for missing packages'
-		PKGcheck
+		echo 'Running check for missing packages' ; PKGcheck
 		for a in "${ArchTixSteps[@]}"; do "$a" || SHOWerror "$a" ; done
 	;;
 	2|Artix|artix)
-		PKGmanager=pacman
-		pkgskips=( --needed --noconfirm )
-		keylayout='KEYMAP=it'
-		keypath='etc/conf.d/keymaps'
-		PKGstrap=basestrap
-		fstabgen=fstabgen
-		chroot='artix-chroot'
-		initc0='rc-update'
-		initc1=add
+		PKGmanager=pacman ; pkgskips=( --needed --noconfirm ) ; keylayout='KEYMAP=it' ; keypath='etc/conf.d/keymaps'
+		PKGstrap=basestrap ; fstabgen=fstabgen ; chroot='artix-chroot' ; initc0='rc-update' ; initc1=add
 		sed -i '/\[lib32]/,/mirrorlist/ s/#//' /etc/pacman.conf
-		if [ "$ARCHrepo" = 1 ]; then
-		ArchRepoSetup /etc/pacman.conf
-		pacman -Sylq system world galaxy lib32 universe extra multilib | sort > pacman_db
-		else pacman -Sylq system world galaxy lib32 | sort > pacman_db
-		fi
-		echo 'Running check for missing packages'
-		PKGcheck
+		if [ "$ARCHrepo" = 1 ]; then ArchRepoSetup /etc/pacman.conf ; pacman -Sylq system world galaxy lib32 universe extra multilib | sort > pacman_db
+		else pacman -Sylq system world galaxy lib32 | sort > pacman_db ; fi
+		echo 'Running check for missing packages' ; PKGcheck
 		for a in "${ArchTixSteps[@]}"; do "$a" || SHOWerror "$a" ; done
 	;;
-	3|Void|void)
-		echo 'nothing here'
-	;;
-	*)
-	;;
+	3|Void|void) echo 'Void installation logic placeholder' ;;
 	esac
 	FinishInst
 }
 
 FinishInst () {
 	echo -e " INSTALLATION COMPLETED \n A copy of the script will be placed in your user home directory"
-	cp "$(pwd)"/Conf_files/bashrc /mnt/etc/bash/bashrc.d/"$UNsel".bashrc
-	#"$chroot" /mnt ln -frs /home/"$UNsel"/.bashrc /etc/bash/bashrc.d/"$UNsel".bashrc
-	mkdir -p /mnt/home/"$UNsel"
-	cp -r "$(pwd)" /mnt/home/"$UNsel"/
+	cp "$(pwd)"/Conf_files/bashrc /mnt/etc/bash/bashrc.d/"$UNsel".bashrc 2>/dev/null || true
+	mkdir -p /mnt/home/"$UNsel" ; cp -r "$(pwd)" /mnt/home/"$UNsel"/
 	sed -i "s/ArchTixUser/$UNsel/g" /mnt/home/"$UNsel"/UNI/full_setup
 	echo 'export MOZ_ENABLE_WAYLAND=1' > /mnt/home/"$UNsel"/.profile
 	cat Errors
-	# a means ugo > u='user that owns files' g='group that owns files' o='all other users' 
-	"$chroot" /mnt chown -hR "$UNsel" /home/"$UNsel"
-	#find /mnt/home/"$UNsel"/"$(pwd)" -type f -exec chmod 644 {} \; # or chmod 755
+	"$chroot" /mnt chown -hR "$UNsel":users /home/"$UNsel"
 	YesNoSel "Reboot system"
 	case "$CC" in
-	1)	umount "$DRIVE"?* && reboot ;;
+	1)	umount -R /mnt && reboot ;;
 	0)	echo 'OK' && exit 0 ;;
 	*)	echo 'Not a good answer' && YesNoSel "Reboot system" ;;
 	esac
 }
 
-PKGcheck () {
-	microcode=("$microcodepkg")
-	#amdgraphics=("${amddrivers[@]}")	#setupped by additional_setup
-	#nvidiagraphics=("${nvidiadrivers[@]}")	#setupped by additional_setup
-	kernel=("$KSel" linux-firmware "$KSel"-headers)
-	baselinux=(base base-devel)
-	baseutils=(man bash-completion kitty vim nano wget git)
-	fs=(dialog mtools parted gptfdisk dosfstools gvfs-mtp) #exfat-utils 
-	bootloaderutility=(efibootmgr os-prober sbsigntools)
-	elogind=(elogind elogind-openrc openrc-settingsd)
-	btrfsutility=(snapper btrfs-progs)
-	grubbtrfs=(grub-btrfs)
-	grubpkg=(grub)
-	refindpkg=(refind)
-	net=(networkmanager iwd chrony chrony-openrc networkmanager-openrc)
-	audio=(pipewire pipewire-pulse pipewire-alsa pipewire-jack wireplumber sof-firmware alsa-card-profiles lib32-pipewire lib32-pipewire-jack)
-	android=(android-tools android-udev)
-	bluetooth=(bluez bluez-utils bluez-openrc blueman)
-	battery=(tlp tlp-openrc)
-	print=(cups cups-pdf system-config-printer avahi avahi-openrc cups-openrc)
-	#xorg=(xorg-server xorg-xinit xorg-xinit light numlockx libinput xorg-xinput xss-lock)
-	apps=(telegram-desktop firefox profile-sync-daemon)
-	utility=(feh gedit calc fd bpytop adriconf fwupd colord colord-openrc) #for netwotk test bmon
-	hardwareacceleration=(libva-mesa-driver mesa-vdpau intel-media-driver vkd3d)
-	vulkan=(vulkan-icd-loader vulkan-intel vulkan-mesa-layers)
-	vulkanlib32=(lib32-vulkan-icd-loader lib32-mesa lib32-vulkan-intel)
-	filemanager=(xed vifm pcmanfm tumbler raw-thumbnailer file-roller)
-	archive=(bzip2 cpio gzip xz lzop p7zip tar unrar zip unzip) # Moved on Aur: atool lha
-	personalization=(cowfortune)
-
-	ProgressBar=0
-	y=" microcode amddrivers nvidiadrivers kernel baselinux baseutils fs bootloaderutility btrfsutility
-	elogind grubpkg grubbtrfs refindpkg net audio bluetooth battery android print apps utility
-	hardwareacceleration vulkan vulkanlib32 filemanager archive xorg personalization "
-
-	for a in $y; do
-		var="$a"'[@]'   #the y element with a [@] to be like an array
-		temp=${!var}  #splitting the every y[@] element inside temp to simulate a subarray
-		#Use IFS=' ' read -r -a temp <<< "${!a}" if you use variable instead of arrays
-		for b in $temp; do   #for every element of subarr temp  
-			if ! pacman -Ss ^"$b"$ 1>/dev/null; then  #check if doesn't exist
-				echo "[x] Package not available: $b from $var"
-				miss+=("$b")    #add missing element to new array miss
-			else new+=("$b")
-			fi
-			ProgressBar=$((ProgressBar+1))
-			echo -ne '['"$ProgressBar"'%]\r'
-		done
-		unset "$a"
-		IFS=" " read -r -a "${a?}" <<< "${new[@]}"
-		unset new
+_chk_add() {
+	for p in "$@"; do
+		if pacman -Ss ^"$p"$ >/dev/null 2>&1; then _valid+=("$p"); else miss+=("$p"); fi
 	done
-	echo 'miss=' "${miss[@]}"
-	for c in $y; do	local d="$c"'[@]' ; echo "$c=""${!d}" ; done
-	if [[ -v miss ]]; then
-		echo "${miss[@]}" | tr ' ' '\n' | sort -u > pkg_missed
-		local i=0 ; while (( "$i" < "${#miss[@]}" )); do echo "${miss[i]}" && i="$((i+1))"; done
-		YesNoSel "Are these packages important to the installation process? A copy will be created in /home/*user*/UNI   -- Type yes or no -- "
-		case $CC in
-		1) echo "OK, we break the installation, edit packages at the end of this file" && exit 0 ;;
-		0) echo "OK, skip those packages and proceed with the installation" ;;
-		*) echo "Do again please" && PkgMissed ;;
-		esac
+}
+
+PKGcheck () {
+	_valid=() ; miss=()
+	# Valida in sequenza tutti gli array dei tuoi pacchetti
+	_chk_add "$microcodepkg" linux-firmware "$KSel" "$KSel"-headers
+	_chk_add base base-devel man bash-completion kitty vim nano wget git
+	_chk_add dialog mtools parted gptfdisk dosfstools gvfs-mtp efibootmgr os-prober sbsigntools
+	_chk_add networkmanager chrony telegram-desktop firefox profile-sync-daemon
+	_chk_add pipewire pipewire-pulse pipewire-alsa pipewire-jack wireplumber sof-firmware alsa-card-profiles
+	_chk_add bluez bluez-utils blueman cups cups-pdf system-config-printer avahi
+	_chk_add feh gedit calc fd bpytop adriconf fwupd colord
+	_chk_add intel-media-driver vkd3d vulkan-icd-loader vulkan-intel vulkan-mesa-layers
+	_chk_add xed vifm pcmanfm tumbler raw-thumbnailer file-roller cowfortune
+	_chk_add bzip2 cpio gzip xz lzop p7zip tar unrar zip unzip
+	
+	# Aggiunte condizionali (OpenRC per Artix, 32-bit e driver Nvidia se selezionati)
+	[ "$OSsel" = Artix ] && _chk_add tlp elogind elogind-openrc openrc-settingsd chrony-openrc networkmanager-openrc bluez-openrc avahi-openrc cups-openrc colord-openrc
+	[ "$FSsel" = btrfs ] && _chk_add snapper btrfs-progs grub-btrfs
+	[ "$BLsel" = grub ]  && _chk_add grub ; [ "$BLsel" = refind ] && _chk_add refind
+	if [[ -v nvidiadrivers ]]; then 
+		_chk_add "${nvidiadrivers[@]}" lib32-vulkan-nvidia lib32-vulkan-icd-loader lib32-mesa lib32-vulkan-intel lib32-pipewire lib32-pipewire-jack
 	fi
-	unset a b c
-	echo "For debug PKGcheck! A=$a B=$b C=$c"
+
+	# Gestione interattiva in caso di pacchetti mancanti (Risolto il vecchio bug del finto ciclo PkgMissed)
+	if [[ -v miss ]]; then
+		echo -e "\n[x] Pacchetti non disponibili:\n$(printf '%s\n' "${miss[@]}" | sort -u)"
+		YesNoSel "Questi pacchetti sono fondamentali? [y = Interrompi / n = Salta e prosegui]"
+		[ "$CC" = 1 ] && echo "Installazione interrotta per pacchetti mancanti." && exit 0
+	fi
 }
 InstallationSetup
 cat Errors
