Update base_install

diff --git a/base_install b/base_install
--- a/base_install
+++ b/base_install
@@ -267,17 +267,19 @@ InstallationSetup () {
 	else ArchTixSteps=( 'DiskPartition' 'FileSystemFormat' 'AdditionalDriveSetup' 'BaseSystemInstall' 'FStabGen' 'SetupEnvironment' 'PackageConfig' 'PackageInstall' 'KernelSetup' 'ServiceSetup' 'UserSetup' 'AudioSetup' 'BootloaderSetup' ) ; fi
 	case "${OSsel,,}" in
 		arch) PKGmanager=pacman; pkgskips=( --needed --noconfirm ); keylayout='KEYMAP=it'; keypath='etc/vconsole.conf'
-			PKGstrap=pacstrap; FSTABgen=genfstab; chroot='arch-chroot'; initc0=systemctl; initc1=enable
-			sed -i '/\[multilib]/,/mirrorlist/ s/#//' /etc/pacman.conf; pacman -Sylq core extra multilib | sort > pacman_db || true
-			echo 'Running check for missing packages'; PKGcheck ;;
+				PKGstrap=pacstrap; FSTABgen=genfstab; chroot='arch-chroot'; initc0=systemctl; initc1=enable
+				sed -i '/\[multilib]/,/mirrorlist/ s/#//' /etc/pacman.conf; pacman -Sylq core extra multilib | sort > pacman_db || true
+				echo 'Running check for missing packages'; PKGcheck ;;
 		artix) PKGmanager=pacman; pkgskips=( --needed --noconfirm ); keylayout='KEYMAP=it'; keypath='etc/conf.d/keymaps'
-			PKGstrap=basestrap; FSTABgen=fstabgen; chroot='artix-chroot'; initc0='rc-update'; initc1=add
-			[[ "$initc0" == "rc-update" ]] && init_sys="openrc" || init_sys="runit"
-			sed -i '/\[lib32]/,/mirrorlist/ s/#//' /etc/pacman.conf
-			if [ "$ARCHrepo" = 1 ]; then ArchRepoSetup /etc/pacman.conf; pacman -Sylq system world galaxy lib32 universe extra multilib | sort > pacman_db || true
-			else pacman -Sylq system world galaxy lib32 | sort > pacman_db || true; fi
-			echo 'Running check for missing packages'; PKGcheck ;;
-		void) echo "Void Linux installation selected: integrating XBPS structures..."; PKGmanager=xbps-install; pkgskips=( -y ); chroot='xbps-uclibc-chroot' ;;
+				PKGstrap=basestrap; FSTABgen=fstabgen; chroot='artix-chroot'; initc0='rc-update'; initc1=add
+				[[ "$initc0" == "rc-update" ]] && init_sys="openrc" || init_sys="runit"
+				sed -i '/\[lib32]/,/mirrorlist/ s/#//' /etc/pacman.conf
+				if [ "$ARCHrepo" = 1 ]; then ArchRepoSetup /etc/pacman.conf; pacman -Sylq system world galaxy lib32 universe extra multilib | sort > pacman_db || true
+				else pacman -Sylq system world galaxy lib32 | sort > pacman_db || true; fi
+				echo 'Running check for missing packages'; PKGcheck ;;
+		void) PKGmanager=xbps-install; pkgskips=( -y -y ); keylayout='KEYMAP=it'; keypath='etc/vconsole.conf'
+				[[ "$LIBsel" == "GLIBC" ]] && VoidArch="x86_64" || VoidArch="x86_64-musl"; VoidRepo="https://voidlinux.org"
+				[[ "$LIBsel" == "MUSL" ]] && VoidRepo+="/musl"; PKGstrap="xbps-install -S -R $VoidRepo -r /mnt $pkgskips" ; chroot="void_chroot" ;;
 	esac
 	if [[ "${OSsel,,}" != "void" ]]; then for a in "${ArchTixSteps[@]}"; do "$a" || SHOWerror "$a"; done; fi
 	FinishInst
