Refactor base_install script for improved paths

diff --git a/base_install b/base_install
--- a/base_install
+++ b/base_install
@@ -13,7 +13,7 @@ SHOWerror () {
 Check_required_files () {
 	local files=( additional_setup full_setup Bootloader/Refind/{refind.conf,refind_linux.conf,themes/Blur-theme/theme.conf}
 			Bootloader/Grub-Eiffel/{theme.txt,select_c.png,select_e.png,select_w.png,eiffel_tower_under_construction.png,icons/arch.png} )
-	for a in "${files[@]}"; do if [ ! -f "$(pwd)/$a" ]; then echo "Missing required file: $a" && local miss+=("$a"); fi
+	for a in "${files[@]}"; do if [ ! -f "${SCRIPT_DIR}/$a" ]; then echo "Missing required file: $a" && local miss+=("$a"); fi; done
 	done
 	if [[ -v miss ]]; then echo 'Required file(s):' "${miss[@]}"
 	else source additional_setup ; fi
@@ -112,10 +112,10 @@ SetupEnvironment () {
 PackageConfig () {
 	"$chroot" /mnt "$PKGmanager" -Sy
 	case "$OSsel" in
-	1|Arch|arch)   sed -i '/\[multilib]/,/mirrorlist/ s/#//' /mnt/etc/pacman.conf ;;
-	2|Artix|artix) sed -i '/\[lib32]/,/mirrorlist/ s/#//' /mnt/etc/pacman.conf
+	Arch|arch)   sed -i '/\[multilib]/,/mirrorlist/ s/#//' /mnt/etc/pacman.conf ;;
+	Artix|artix) sed -i '/\[lib32]/,/mirrorlist/ s/#//' /mnt/etc/pacman.conf
 				   [ "$ARCHrepo" = 1 ] && ArchRepoSetup /mnt/etc/pacman.conf ;;
-	3|Void|void)   ;;
+	Void|void)   ;;
 	*) echo "Error distro configuration" && exit 1 ;;
 	esac
 	sed -i '/\(Color\|ParallelDownloads\)/ s/#//' /mnt/etc/pacman.conf
@@ -173,7 +173,7 @@ ServiceSetup () {
 	if [[ -v nvidiadrivers ]] && [ "$OSsel" = Artix ]; then Services+=( nvidia-persistenced ); fi
 	for s in "${Services[@]}"; do "$chroot" /mnt "$initc0" "$initc1" "$s" ; done
 	mkdir -p /mnt/etc/udev/rules.d/
-	cp ../UNI/Conf_files/51-android.rules /mnt/etc/udev/rules.d/
+	cp "${SCRIPT_DIR}/Conf_files/51-android.rules" /mnt/etc/udev/rules.d/
 }
 
 UserSetup () {
@@ -225,7 +225,7 @@ BootloaderSetup () {
 		cp ../UNI/Bootloader/Refind/refind_linux.conf /mnt/boot/refind_linux.conf
 		cp -r ../UNI/Bootloader/Refind/themes/* /mnt/boot/EFI/"$efifolder"/themes/
 		if [ "$FSsel" = btrfs ]; then rootflags='rootflags=subvol=@' ; fi
-		if [[ -v nvidiadrivers ]]; then drm="nvidia-drm.modeset=1 nvidia-drm.fbdev=1 acpi_osi='Windows 2020'" ; fi
+		if [[ -v nvidiadrivers ]]; then drm="nvidia-drm.modeset=1 nvidia-drm.fbdev=1 acpi_osi=\"Windows 2020\"" ; fi
 		echo "\"Standard Boot\"   \"ro root=$ROOTID rootfstype=$FSsel $rootflags initrd=boot\\${microcodepkg}.img initrd=boot\\${irfs} $drm\"" >> /mnt/boot/refind_linux.conf
 		echo '!!!Refind config and theme changed!!!'
 	;;
@@ -252,10 +252,10 @@ BootloaderSetup () {
 	;;
 	3|EFISTUB|Efistub|efistub)
 		if [ "$FSsel" = btrfs ]; then rootflags='rootflags=subvol=@' ; fi
-		if [[ -v nvidiadrivers ]]; then osi="nvidia-drm.modeset=1 nvidia-drm.fbdev=1 acpi_osi='Windows 2020'" ; fi
+		if [[ -v nvidiadrivers ]]; then osi="nvidia-drm.modeset=1 nvidia-drm.fbdev=1 acpi_osi=\"Windows 2020\"" ; fi
 		if [[ "$IRFSetup" = booster ]]; then irfs="booster.img"; else irfs="initramfs-$KSel.img"; fi
-		BLflags="\"ro root=$ROOTID rootfstype=$FSsel $rootflags initrd=\\$microcodepkg.img initrd=\\$irfs $osi\""
-		"$chroot" /mnt efibootmgr -d "$BOOT_PART" -p 1 -c -L "$OSsel" -l /vmlinuz-"$KSel" -u "$BLflags" --verbose
+		BLflags="ro root=$ROOTID rootfstype=$FSsel $rootflags initrd=\\${microcodepkg}.img initrd=\\${irfs} $osi"
+		"$chroot" /mnt efibootmgr -d "$BOOT_PART" -p 1 -c -L "$OSsel" -l "\\vmlinuz-$KSel" -u "$BLflags" --verbose
 		echo "efibootmgr -b lastnumber -B" 
 	;;
 	*)	exit 1
@@ -315,7 +315,7 @@ InstallationSetup () {
 	fi
 	
 	case "$OSsel" in
-	1|Arch|arch)
+	Arch|arch)
 		PKGmanager=pacman ; pkgskips=( --needed --noconfirm ) ; keylayout='KEYMAP=it' ; keypath='etc/vconsole.conf'
 		PKGstrap=pacstrap ; fstabgen=genfstab ; chroot='arch-chroot' ; initc0=systemctl ; initc1=enable
 		sed -i '/\[multilib]/,/mirrorlist/ s/#//' /etc/pacman.conf
@@ -323,7 +323,7 @@ InstallationSetup () {
 		echo 'Running check for missing packages' ; PKGcheck
 		for a in "${ArchTixSteps[@]}"; do "$a" || SHOWerror "$a" ; done
 	;;
-	2|Artix|artix)
+	Artix|artix)
 		PKGmanager=pacman ; pkgskips=( --needed --noconfirm ) ; keylayout='KEYMAP=it' ; keypath='etc/conf.d/keymaps'
 		PKGstrap=basestrap ; fstabgen=fstabgen ; chroot='artix-chroot' ; initc0='rc-update' ; initc1=add
 		sed -i '/\[lib32]/,/mirrorlist/ s/#//' /etc/pacman.conf
@@ -332,15 +332,15 @@ InstallationSetup () {
 		echo 'Running check for missing packages' ; PKGcheck
 		for a in "${ArchTixSteps[@]}"; do "$a" || SHOWerror "$a" ; done
 	;;
-	3|Void|void) echo 'Void installation logic placeholder' ;;
+	Void|void) echo 'Void installation logic placeholder' ;;
 	esac
 	FinishInst
 }
 
 FinishInst () {
 	echo -e " INSTALLATION COMPLETED \n A copy of the script will be placed in your user home directory"
-	cp "$(pwd)"/Conf_files/bashrc /mnt/etc/bash/bashrc.d/"$UNsel".bashrc 2>/dev/null || true
-	mkdir -p /mnt/home/"$UNsel" ; cp -r "$(pwd)" /mnt/home/"$UNsel"/
+	cp "${SCRIPT_DIR}"/Conf_files/bashrc /mnt/etc/bash/bashrc.d/"$UNsel".bashrc 2>/dev/null || true
+	mkdir -p /mnt/home/"$UNsel" ; cp -r "${SCRIPT_DIR}" /mnt/home/"$UNsel"/
 	sed -i "s/ArchTixUser/$UNsel/g" /mnt/home/"$UNsel"/UNI/full_setup
 	echo 'export MOZ_ENABLE_WAYLAND=1' > /mnt/home/"$UNsel"/.profile
 	cat Errors
