Update installation logic for Arch, Artix, and Void
Refactor installation setup for various operating systems.

diff --git a/base_install b/base_install
--- a/base_install
+++ b/base_install
@@ -284,22 +284,19 @@ InstallationSetup () {
 	else SHOWerror InstallationSetup; fi
 	local s_step; [[ "${OSsel,,}" == "void" ]] && s_step='VoidSystemInstall' || s_step='ArchTixSystemInstall'
 	[[ "$VBTsel" == "1" ]] && ArchTixSteps=( 'DiskPartition' 'FileSystemFormat' "$s_step" 'FStabGen' 'SetupEnvironment' 'PackageConfig' 'PackageInstall' 'KernelSetup' 'ServiceSetup' 'UserSetup' 'BootloaderSetup' ) || ArchTixSteps=( 'DiskPartition' 'FileSystemFormat' 'AdditionalDriveSetup' "$s_step" 'FStabGen' 'SetupEnvironment' 'PackageConfig' 'PackageInstall' 'KernelSetup' 'ServiceSetup' 'UserSetup' 'AudioSetup' 'BootloaderSetup' )
-	case "${OSsel,,}" in
-		arch) PKGmanager=pacman; PKGquery=pacman; pkgskips=( --needed --noconfirm ); keylayout='KEYMAP=it'; keypath='etc/vconsole.conf'; PKGstrap=pacstrap; FSTABgen=genfstab; chroot='arch-chroot'; initc0=systemctl; initc1=enable
-			sed -i -e 's/^#ParallelDownloads = 5/ParallelDownloads = 5/' -e '/\[multilib]/,/mirrorlist/ s/#//' /etc/pacman.conf
-			pacman -Sylq core extra multilib | sort > pacman_db || true
-			echo 'Running check for missing packages'; PKGcheck ;;
-		artix) PKGmanager=pacman; PKGquery=pacman; pkgskips=( --needed --noconfirm ); keylayout='KEYMAP=it'; keypath='etc/conf.d/keymaps'; PKGstrap=basestrap; FSTABgen=fstabgen; chroot='artix-chroot'; initc0='rc-update'; initc1=add
-			[[ "$initc0" == "rc-update" ]] && init_sys="openrc" || init_sys="runit"
-			sed -i -e 's/^#ParallelDownloads = 5/ParallelDownloads = 5/' -e '/\[lib32]/,/mirrorlist/ s/#//' /etc/pacman.conf
-			if [[ "$ARCHrepo" == "1" ]]; then ArchRepoSetup /etc/pacman.conf; pacman -Sylq system world galaxy lib32 universe extra multilib | sort > pacman_db || true
-			else pacman -Sylq system world galaxy lib32 | sort > pacman_db || true; fi
-			echo 'Running check for missing packages'; PKGcheck ;;
-		void) PKGmanager=xbps-install; PKGquery=xbps-query; pkgskips=( -y -y ); keylayout='KEYMAP=it'; keypath='etc/rc.conf'
-			[[ "$LIBsel" == "GLIBC" ]] && VoidArch="x86_64" || VoidArch="x86_64-musl"
-			VoidRepo="https://voidlinux.org"
-			[[ "$LIBsel" == "MUSL" ]] && VoidRepo+="/musl"; PKGstrap="xbps-install -S -R $VoidRepo -r /mnt ${pkgskips[*]}"; chroot="chroot" ;;
-	esac
+	if [[ "${OSsel,,}" != "void" ]]; then
+		PKGmanager=pacman; PKGquery=pacman; pkgskips=( --needed --noconfirm ); keylayout='KEYMAP=it'; chroot="${OSsel,,}-chroot"
+		if		[[ "${OSsel,,}" == "arch" ]]; then keypath='etc/vconsole.conf'; PKGstrap=pacstrap; FSTABgen=genfstab; initc0=systemctl; initc1=enable
+				sed -i -e 's/^#ParallelDownloads = 5/ParallelDownloads = 5/' -e '/\[multilib]/,/mirrorlist/ s/#//' /etc/pacman.conf; pacman -Sylq core extra multilib | sort > pacman_db || true
+		elif	[[ "${OSsel,,}" == "artix" ]]; then keypath='etc/conf.d/keymaps'; PKGstrap=basestrap; FSTABgen=fstabgen; initc0='rc-update'; initc1=add
+				[[ "$initc0" == "rc-update" ]] && init_sys="openrc" || init_sys="runit"; sed -i -e 's/^#ParallelDownloads = 5/ParallelDownloads = 5/' -e '/\[lib32]/,/mirrorlist/ s/#//' /etc/pacman.conf
+				[[ "$ARCHrepo" == "1" ]] && ArchRepoSetup /etc/pacman.conf; pacman -Sylq system world galaxy lib32 $([[ "$ARCHrepo" == "1" ]] && echo "universe extra multilib") | sort > pacman_db || true
+		fi
+	echo 'Running check for missing packages'; PKGcheck
+	else
+		PKGmanager=xbps-install; PKGquery=xbps-query; pkgskips=( -y -y ); keylayout='KEYMAP=it'; keypath='etc/rc.conf'; [[ "$LIBsel" == "GLIBC" ]] && VoidArch="x86_64" || VoidArch="x86_64-musl"
+		VoidRepo="https://voidlinux.org$([[ "$LIBsel" == "MUSL" ]] && echo "/musl")"; PKGstrap="xbps-install -S -R $VoidRepo -r /mnt ${pkgskips[*]}"; chroot="chroot"
+	fi
 	for a in "${ArchTixSteps[@]}"; do "$a" || SHOWerror "$a"; done
 	FinishInst
 }
