Update base_install

diff --git a/base_install b/base_install
--- a/base_install
+++ b/base_install
@@ -2,7 +2,7 @@
 if [ "$(id -u)" -ne 0 ]; then echo 'Please run as root.' >&2; exit 1; fi
 
 Show_error () {
-	echo "Error in function >> ${FUNCNAME[1]} <<" >&2 && exit 1
+	echo "Error in function $1 >> ${FUNCNAME[1]} <<" >&2 && exit 1
 }
 
 Check_required_files () {
