Update installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -396,22 +396,33 @@ UserSetup () {
 		if [[ "$DEsel" == "Hyprland" && -d "${SCRIPT_DIR}/Conf_files/Hyprland" ]]; then cp -a "${SCRIPT_DIR}/Conf_files/Hyprland/." /mnt/home/"$UNsel"/.config/hypr/ ; touch /mnt/home/"$UNsel"/.config/hypr/hyprpaper.conf ; fi
 		if [[ "$DEsel" == "Niri" && -d "${SCRIPT_DIR}/Conf_files/Niri" ]]; then cp -r "${SCRIPT_DIR}/Conf_files/Niri" /mnt/home/"$UNsel"/.config/niri ; fi
 		"$chroot" /mnt chmod +x /home/"$UNsel"/.config/wallpapers/theme-switcher.sh
+		
+		echo -e "auth required pam_unix.so\naccount required pam_unix.so\npassword required pam_unix.so\nsession required pam_unix.so" > /mnt/etc/pam.d/hyprlock
+		"$chroot" /mnt chmod u+s /usr/bin/unix_chkpwd 2>/dev/null || "$chroot" /mnt chmod u+s /sbin/unix_chkpwd 2>/dev/null
+		
 		local t_files=()
 		if [[ "$DEsel" == "Niri" ]]; then t_files=( "/mnt/home/$UNsel/.config/niri/config.kdl" "/mnt/home/$UNsel/.config/wallust/templates/colors-niri.conf" ) ; fi
 		if [[ "$DEsel" == "Hyprland" ]]; then t_files=( "/mnt/home/$UNsel/.config/hypr/hyprland.conf" "/mnt/home/$UNsel/.config/wallust/templates/colors-hyprland.conf" ) ; fi
 		for f in "${t_files[@]}"; do
 			if [[ ! -f "$f" ]]; then continue ; fi
 			if [[ "$VBTsel" -eq 1 ]]; then
-				if [[ "$DEsel" == "Niri" ]]; then
-					if grep -q "environment *{" "$f"; then	grep -q 'LIBGL_ALWAYS_SOFTWARE' "$f" || sed -i '/environment *{/a\	LIBGL_ALWAYS_SOFTWARE "1"' "$f"
-					else echo -e '\nenvironment {\n	LIBGL_ALWAYS_SOFTWARE "1"\n}' >> "$f" ; fi
-					grep -q 'VBoxClient' "$f" || sed -i -e '/spawn-at-startup/{i\spawn-at-startup "VBoxClient" "--clipboard"' -e ':a;n;ba}' "$f"
+				local is_qemu=0 ; if lspci | grep -Eqi "(VMware|Virtio|QXL)"; then is_qemu=1 ; fi
+				if [[ "$DEsel" == "Niri" && "$f" == *config.kdl ]]; then
+					if grep -q "environment *{" "$f"; then    grep -q 'LIBGL_ALWAYS_SOFTWARE' "$f" || sed -i '/environment *{/a\    LIBGL_ALWAYS_SOFTWARE "1"' "$f"
+					else echo -e '\nenvironment {\n    LIBGL_ALWAYS_SOFTWARE "1"\n}' >> "$f" ; fi
+					grep -q 'output "Virtual-1"' "$f" || echo -e '\noutput "Virtual-1" {\n    mode "1920x1080"\n}' >> "$f"
+					if [[ "$is_qemu" -eq 1 ]]; then grep -q 'spice-vdagent' "$f" || sed -i -e '/spawn-at-startup/{i\spawn-at-startup "spice-vdagent"' -e ':a;n;ba}' "$f"
+					else grep -q 'VBoxClient' "$f" || sed -i -e '/spawn-at-startup/{i\spawn-at-startup "VBoxClient" "--clipboard"' -e ':a;n;ba}' "$f" ; fi
 					sed -i 's/blur true/blur false/g' "$f"
 				fi
-				if [[ "$DEsel" == "Hyprland" && "$f" == *hyprland.conf ]]; then sed -i -e '/exec-once/{i\exec-once = VBoxClient --clipboard' -e ':a;n;ba}' "$f" ; fi
+				if [[ "$DEsel" == "Hyprland" && "$f" == *hyprland.conf ]]; then
+					grep -q 'monitor=,1920x1080' "$f" || sed -i '1i monitor=,1920x1080@60,auto,1' "$f"
+					if [[ "$is_qemu" -eq 1 ]]; then sed -i -e '/exec-once/{i\exec-once = spice-vdagent' -e ':a;n;ba}' "$f"
+					else sed -i -e '/exec-once/{i\exec-once = VBoxClient --clipboard' -e ':a;n;ba}' "$f" ; fi
+				fi
 			fi
 			if [[ "${OSsel,,}" != "arch" && "$init_sys" != "systemd" ]]; then
-				if [[ "$DEsel" == "Niri" ]]; then sed -i -e '/spawn-at-startup/{i\spawn-at-startup "bash" "-c" "pipewire & sleep 1; wireplumber & pipewire-pulse &"' -e ':a;n;ba}' "$f" ; fi
+				if [[ "$DEsel" == "Niri" && "$f" == *config.kdl ]]; then sed -i -e '/spawn-at-startup/{i\spawn-at-startup "bash" "-c" "pipewire & sleep 1; wireplumber & pipewire-pulse &"' -e ':a;n;ba}' "$f" ; fi
 				if [[ "$DEsel" == "Hyprland" && "$f" == *hyprland.conf ]]; then sed -i -e '/exec-once/{i\exec-once = bash -c "pipewire & sleep 1; wireplumber & pipewire-pulse &"' -e ':a;n;ba}' "$f" ; fi
 			fi
 		done
